# Generated by Django 5.2.15 on 2026-06-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='cargas/')),
                ('tipo_archivo', models.CharField(choices=[('IMP', 'Importaciones'), ('EXP_BASE', 'Exportaciones Base'), ('EXP_BULTO', 'Exportaciones Bultos'), ('EXP_DOC', 'Exportaciones Documentos de Transporte')], max_length=16)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('PROCESADO', 'Procesado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=32)),
                ('periodo_anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('total_ok', models.PositiveIntegerField(default=0)),
                ('total_error', models.PositiveIntegerField(default=0)),
                ('observacion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
