# Generated by Django 5.2.15 on 2026-06-13 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCargaStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_linea', models.PositiveIntegerField()),
                ('raw_line', models.TextField()),
                ('data_json', models.JSONField(default=dict)),
                ('procesado', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('archivo_carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging', to='comercio.archivocarga')),
            ],
            options={
                'ordering': ['nro_linea'],
                'unique_together': {('archivo_carga', 'nro_linea')},
            },
        ),
    ]
