# Generated by Django 5.2.15 on 2026-06-14 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0002_archivocargastaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('numero_ident', models.CharField(blank=True, max_length=64)),
                ('item', models.CharField(blank=True, max_length=32)),
                ('fecha_text', models.CharField(blank=True, max_length=32)),
                ('fecha_date', models.DateField(blank=True, null=True)),
                ('aduana_codigo', models.CharField(blank=True, max_length=32)),
                ('pais_destino_codigo', models.CharField(blank=True, max_length=32)),
                ('via_transporte_codigo', models.CharField(blank=True, max_length=32)),
                ('partida_arancelaria_codigo', models.CharField(blank=True, max_length=32)),
                ('glosa_mercancia', models.TextField(blank=True)),
                ('valor_fob', models.CharField(blank=True, max_length=32)),
                ('payload_json', models.JSONField(default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('archivo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to='comercio.archivocarga')),
            ],
        ),
        migrations.CreateModel(
            name='ExportacionBulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('numero_ident', models.CharField(blank=True, max_length=64)),
                ('secuencia', models.CharField(blank=True, max_length=32)),
                ('tipo_bulto_codigo', models.CharField(blank=True, max_length=32)),
                ('cantidad_bultos', models.CharField(blank=True, max_length=32)),
                ('marcas', models.CharField(blank=True, max_length=255)),
                ('payload_json', models.JSONField(default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('archivo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bultos', to='comercio.archivocarga')),
            ],
        ),
        migrations.CreateModel(
            name='ExportacionDocTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('numero_ident', models.CharField(blank=True, max_length=64)),
                ('secuencia', models.CharField(blank=True, max_length=32)),
                ('numero_documento', models.CharField(blank=True, max_length=64)),
                ('fecha_documento_text', models.CharField(blank=True, max_length=32)),
                ('nave', models.CharField(blank=True, max_length=255)),
                ('numero_viaje', models.CharField(blank=True, max_length=64)),
                ('puerto_embarque_codigo', models.CharField(blank=True, max_length=32)),
                ('via_transporte_codigo', models.CharField(blank=True, max_length=32)),
                ('payload_json', models.JSONField(default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('archivo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_transporte', to='comercio.archivocarga')),
            ],
        ),
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('periodo_mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('numero_ident', models.CharField(blank=True, max_length=64)),
                ('item', models.CharField(blank=True, max_length=32)),
                ('fecha_text', models.CharField(blank=True, max_length=32)),
                ('fecha_date', models.DateField(blank=True, null=True)),
                ('aduana_codigo', models.CharField(blank=True, max_length=32)),
                ('pais_origen_codigo', models.CharField(blank=True, max_length=32)),
                ('via_transporte_codigo', models.CharField(blank=True, max_length=32)),
                ('partida_arancelaria_codigo', models.CharField(blank=True, max_length=32)),
                ('glosa_mercancia', models.TextField(blank=True)),
                ('valor_fob', models.CharField(blank=True, max_length=32)),
                ('valor_flete', models.CharField(blank=True, max_length=32)),
                ('valor_seguro', models.CharField(blank=True, max_length=32)),
                ('valor_cif', models.CharField(blank=True, max_length=32)),
                ('payload_json', models.JSONField(default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('archivo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to='comercio.archivocarga')),
            ],
        ),
    ]
