# Generated by Django 5.2.15 on 2026-06-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0003_exportacion_exportacionbulto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivocarga',
            name='total_procesados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
