# Generated by Django 5.2.15 on 2026-06-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0004_archivocarga_total_procesados'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacion',
            name='comuna_importador_codigo',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
