# Generated by Django 5.2.15 on 2026-10-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0007_importacion_periodo_creado_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportacion',
            name='cantidad_mercancia',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='comuna_exportador_codigo',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='exportador_codigo',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='peso_bruto_item',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='puerto_desembarque_codigo',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='puerto_embarque_codigo',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='region_origen_codigo',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='registro_incompleto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='tipo_operacion_codigo',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='unidad_medida_codigo',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='valor_cif_dus',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='valor_flete_dus',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='valor_fob_dus',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='valor_fob_unitario',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='valor_liquido_retorno_dus',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='valor_seguro_dus',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportacionbulto',
            name='fecha_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportacionbulto',
            name='fecha_text',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportaciondoctransporte',
            name='fecha_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportaciondoctransporte',
            name='fecha_text',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='exportaciondoctransporte',
            name='registro_incompleto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='exportacion',
            index=models.Index(fields=['periodo_anio', 'periodo_mes'], name='exp_periodo_idx'),
        ),
        migrations.AddIndex(
            model_name='exportacion',
            index=models.Index(fields=['numero_ident'], name='exp_numero_ident_idx'),
        ),
        migrations.AddIndex(
            model_name='exportacion',
            index=models.Index(fields=['partida_arancelaria_codigo'], name='exp_partida_idx'),
        ),
        migrations.AddIndex(
            model_name='exportacionbulto',
            index=models.Index(fields=['periodo_anio', 'periodo_mes'], name='exp_bulto_periodo_idx'),
        ),
        migrations.AddIndex(
            model_name='exportacionbulto',
            index=models.Index(fields=['numero_ident'], name='exp_bulto_numero_ident_idx'),
        ),
        migrations.AddIndex(
            model_name='exportaciondoctransporte',
            index=models.Index(fields=['periodo_anio', 'periodo_mes'], name='exp_doc_periodo_idx'),
        ),
        migrations.AddIndex(
            model_name='exportaciondoctransporte',
            index=models.Index(fields=['numero_ident'], name='exp_doc_numero_ident_idx'),
        ),
    ]
