# Generated by Django 5.2.15 on 2026-10-10 00:22

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0008_exportaciones_dus_campos'),
    ]

    operations = [
        TrigramExtension(),  # pg_trgm is a trusted extension: the database owner can create it.
        migrations.AddField(
            model_name='exportacion',
            name='texto_producto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='importacion',
            name='texto_producto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
