# Generated by Django 5.2.15 on 2026-06-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaArancelaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('glosa', models.CharField(max_length=255)),
                ('vigente', models.BooleanField(default=True)),
                ('origen', models.CharField(default='INICIAL', max_length=32)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Partida arancelaria',
                'verbose_name_plural': 'Partidas arancelarias',
            },
        ),
        migrations.CreateModel(
            name='CatalogoCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=64)),
                ('glosa', models.CharField(blank=True, max_length=255)),
                ('vigente', models.BooleanField(default=True)),
                ('origen', models.CharField(default='INICIAL', max_length=32)),
                ('pendiente_revision', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True)),
                ('grupo', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Catálogo de código',
                'verbose_name_plural': 'Catálogos de códigos',
                'unique_together': {('grupo', 'codigo')},
            },
        ),
    ]
