# Generated by Django 5.2.15 on 2026-06-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogocodigo',
            name='codigo',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='catalogocodigo',
            name='grupo',
            field=models.CharField(max_length=96),
        ),
    ]
