# Generated by Django 5.2.15 on 2026-06-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_catalogocodigo_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogocodigo',
            name='glosa',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partidaarancelaria',
            name='glosa',
            field=models.TextField(),
        ),
    ]
