# Generated by Django 5.2.15 on 2026-08-28 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportadorProbable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=16)),
                ('dv', models.CharField(blank=True, max_length=4)),
                ('nombre', models.CharField(max_length=255)),
                ('origen', models.CharField(default='REPORTE_SECTORIAL', max_length=32)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('rut', 'dv', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ReporteSectorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('rubro', models.CharField(max_length=128)),
                ('periodo_anio', models.PositiveSmallIntegerField()),
                ('periodo_mes', models.PositiveSmallIntegerField()),
                ('hoja_base', models.CharField(max_length=128)),
                ('ruta_origen', models.TextField()),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-periodo_anio', '-periodo_mes', 'rubro'],
                'unique_together': {('nombre_archivo', 'hoja_base')},
            },
        ),
        migrations.CreateModel(
            name='ReporteSectorialDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_linea', models.PositiveIntegerField()),
                ('rut', models.CharField(blank=True, max_length=16)),
                ('dv', models.CharField(blank=True, max_length=4)),
                ('aduana_nombre', models.CharField(blank=True, max_length=128)),
                ('pais_origen_nombre', models.CharField(blank=True, max_length=128)),
                ('partida_arancelaria_codigo', models.CharField(blank=True, max_length=32)),
                ('mercaderia', models.TextField(blank=True)),
                ('valor_fob', models.CharField(blank=True, max_length=32)),
                ('valor_flete', models.CharField(blank=True, max_length=32)),
                ('valor_seguro', models.CharField(blank=True, max_length=32)),
                ('valor_cif', models.CharField(blank=True, max_length=32)),
                ('payload_json', models.JSONField(default=dict)),
                ('importador_probable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias', to='reportes.importadorprobable')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='reportes.reportesectorial')),
            ],
            options={
                'ordering': ['nro_linea'],
                'unique_together': {('reporte', 'nro_linea')},
            },
        ),
    ]
