# Generated by Django 5.2.15 on 2026-08-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportesectorial',
            name='es_acumulado',
            field=models.BooleanField(default=False),
        ),
    ]
