# Generated by Django 5.2.15 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("reportes", "0002_reportesectorial_es_acumulado")]

    operations = [
        migrations.CreateModel(
            name="RubroImportacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("configuracion_json", models.JSONField(default=dict)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["nombre"]},
        ),
    ]
