# Generated by Django 5.2.15 on 2026-10-08 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_perfilimportador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='IMP', max_length=16)),
                ('parametros_json', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('LISTO', 'Listo'), ('ERROR', 'Error')], default='PENDIENTE', max_length=16)),
                ('filas_total', models.PositiveIntegerField(default=0)),
                ('filas_procesadas', models.PositiveIntegerField(default=0)),
                ('archivo', models.CharField(blank=True, max_length=255)),
                ('nombre_descarga', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_excel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
