# Generated by Django 5.2.15 on 2026-10-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_informeexcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubroimportacion',
            name='tipo',
            field=models.CharField(choices=[('IMP', 'Importaciones'), ('EXP', 'Exportaciones')], default='IMP', max_length=3),
        ),
        migrations.AlterField(
            model_name='rubroimportacion',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='rubroimportacion',
            constraint=models.UniqueConstraint(fields=('tipo', 'nombre'), name='rubro_tipo_nombre_uniq'),
        ),
    ]
